### PR TITLE
IT: fix flaky HeartbeatTests.HeartbeatFailed test

### LINKED ISSUE #395: HeartbeatTests.Integration_Cassandra_HeartbeatFailed is flaky
Failing run: https://github.com/scylladb/cpp-rs-driver/actions/runs/19855928458/job/56894430328?pr=393

[ RUN      ] HeartbeatTests.Integration_Cassandra_HeartbeatFailed
1764673526810 [DEBUG] (scylla_cpp_driver::logging:177) message: Log level is set to TRACE
ccm> ccm list
ccm> ccm list
ccm> ccm list
ccm> ccm stop
ccm> ccm status
ccm> ccm create --scylla -n 2:0 -i 127.0.0. --version=release:2025.2.2 -b cpp-driver_2025-2-2_2-0
ccm> ccm updateconf --rt=10000 read_request_timeout_in_ms:10000 write_request_timeout_in_ms:10000 request_timeout_in_ms:10000 phi_convict_threshold:16 hinted_handoff_enabled:false enable_materialized_views:true dynamic_snitch_update_interval_in_ms:1000 native_transport_max_threads:1 concurrent_reads:2 concurrent_writes:2 concurrent_compactors:1 compaction_throughput_mb_per_sec:0 key_cache_size_in_mb:0 key_cache_save_period:0 memtable_flush_writers:1 max_hints_delivery_threads:1 cas_contention_timeout_in_ms:10000 file_cache_size_in_mb:0
ccm> ccm start --wait-other-notice --wait-for-binary-proto --jvm_arg=--skip-wait-for-gossip-to-settle=0
ccm> ccm status
ccm> ccm node2 pause
ccm> ccm node2 resume
/home/runner/work/cpp-rs-driver/cpp-rs-driver/tests/src/integration/tests/test_heartbeat.cpp:102: Failure
ccm> ccm list
Expected: (metrics.stats.total_connections) < (initial_connections), actual: 3 vs 3
[  FAILED  ] HeartbeatTests.Integration_Cassandra_HeartbeatFailed (70629 ms)

### PR DESCRIPTION
**Pull request by dkropachev**
## Summary
- Fix flaky `HeartbeatTests.Integration_Cassandra_HeartbeatFailed` test by using 1 connection per host (`with_core_connections_per_host(1)`) instead of the default per-shard pool
- The default pool size causes asynchronous shard-aware connection establishment to race with the baseline `total_connections` count read, making the count non-deterministic and the assertion flaky

Fixes #395

## Test plan
- [x] Run `HeartbeatTests.Integration_Cassandra_HeartbeatFailed` repeatedly to verify it no longer flakes

### CODE REVIEW

**Review by wprzytula — COMMENTED** [review]
Explanations from the cover letter and the commit message are different, although not mutually exclusive. I'm confused.
Cover letter mentions completing TCP handshakes to SIGSTOP'ed nodes, while the commit message mentions additional connections opened asynchronously to shards.

File: tests/src/integration/tests/test_heartbeat.cpp [hunk 1]
```diff
@@ -88,7 +88,21 @@ CASSANDRA_INTEGRATION_TEST_F(HeartbeatTests, HeartbeatFailed) {
...
   cass_uint64_t initial_connections = session_.metrics().stats.total_connections;
+  for (int i = 0; i < 10; ++i) {
+    msleep(100);
+    cass_uint64_t current = session_.metrics().stats.total_connections;
+    if (current != initial_connections) {
+      initial_connections = current;
+      i = 0; // Reset: connections still changing
+    }
+  }
+
```
Comment (wprzytula) [inline tests/src/integration/tests/test_heartbeat.cpp]: 💭 This adds a minimum of 1s delay to the test. Am I correct?

File: tests/src/integration/tests/test_heartbeat.cpp [hunk 2]
```diff
@@ -88,7 +88,21 @@ CASSANDRA_INTEGRATION_TEST_F(HeartbeatTests, HeartbeatFailed) {
...
+  // from killed connections on the paused node.
   cass_uint64_t initial_connections = session_.metrics().stats.total_connections;
+  for (int i = 0; i < 10; ++i) {
+    msleep(100);
+    cass_uint64_t current = session_.metrics().stats.total_connections;
+    if (current != initial_connections) {
+      initial_connections = current;
+      i = 0; // Reset: connections still changing
+    }
+  }
```
Comment (Lorak-mmk) [inline tests/src/integration/tests/test_heartbeat.cpp]: Instead of adding sleeps, maybe you could use `cass_cluster_set_core_connections_per_host(cluster, 1)`? Then there would be only 1 conn per host, and there should be no delay, and so no sleeps needed.

**Review by Lorak-mmk — CHANGES_REQUESTED** [review]

File: tests/src/integration/tests/test_heartbeat.cpp (hunk 2 above)
Comment (dkropachev) [reply tests/src/integration/tests/test_heartbeat.cpp]: good suggestion, merged and tested, no single failure in 100 runs.

**Comment by wprzytula** [comment]
> Explanations from the cover letter and the commit message are different, although not mutually exclusive. I'm confused. Cover letter mentions completing TCP handshakes to SIGSTOP'ed nodes, while the commit message mentions additional connections opened asynchronously to shards.

@dkropachev can you explain?

File: tests/src/integration/tests/test_heartbeat.cpp (hunk 1 above)
Comment (dkropachev) [reply tests/src/integration/tests/test_heartbeat.cpp]: This part is chaned

**Comment by dkropachev** [comment]
> > Explanations from the cover letter and the commit message are different, although not mutually exclusive. I'm confused. Cover letter mentions completing TCP handshakes to SIGSTOP'ed nodes, while the commit message mentions additional connections opened asynchronously to shards.
> 
> @dkropachev can you explain?

Forgot to update it, I have changed code twice since PR description was created.
Please check now

**Review by Lorak-mmk — APPROVED** [review]

**Review by wprzytula — APPROVED** [review]
