### PR TITLE
ci: fix skipped tests

### LINKED ISSUE #144: CI: some tests are unnecessarily skipped when run against Scylla
A simple example are tests for `duration` cql type:
```
[SKIPPED] Unsupported for Apache Cassandra Version 3.0.8: Server version 3.10+ is required
[OK]      CassandraTypesDurationTests.Integration_Cassandra_MixedValues (1937 ms)
```

When scylla cluster is set up via ccm (no matter the version of scylla), the `ccm <node> version` command always returns a `3.0.8` version. This version is probably hardcoded in `nodetool` (`ccm <node> version` command delegates it to `nodetool`). However, there is a way to print a scylla version using ccm. There is a `ccm <node> versionfrombuild` command which seems to display the correct version of scylla node.

We need to adjust the logic responsible for filtering out the tests based on Scylla/Cassandra version. Testing framework should be aware whether it's used against Cassandra or Scylla cluster, and then execute either `ccm <node> version` or `ccm <node> versionfrombuild` respectively. Minimal versions required for specific tests should be adjusted for scylla, because I believe that there is no 1:1 mapping between Scylla's and Cassandra's versions and some features were probably introduced in different versions.

### PR DESCRIPTION
**Pull request by muzarski**
Fix: https://github.com/scylladb/cpp-rust-driver/issues/144

This PR addresses multiple issues:
## Skipped tests for scylla clusters
As linked issue mentions, `ccm <node> version` for scylla clusters always returns `3.0.8` version which I believe is hardcoded. Because of that, some tests were unnecessarily skipped. To retrieve scylla version, we should use `ccm <node> versionfrombuild`.

I adjusted the logic for retrieving the Scylla version. Apart from that, I skip the version checks for Scylla, since the feature to version mapping is not the same for Scylla and Cassandra. I left the checks for Cassandra. As of now, I don't think it's really important to check which features should be tested based on Scylla version, since we don't plan to test old Scylla versions. We will add such filters in the future, once they are needed.

## No compact test
Previously, this test was silently passing as it was skipped for both Scylla and Cassandra. However, the function `cass_cluster_set_no_compact` is not even implemented. I removed this test from CI (for both Scylla and Cassandra).

## Map collection iterator
cpp-rust-driver's implementation of `cass_iterator_from_collection` for maps was inconsistent with cpp-driver's implementation. This PR fixes it. I found this bug, because the test for a `map<int, duration>` type was handled a bit differently than for the other types (since apparently, `duration` cannot be used as a primary key). This test was failing due to the bug with map iterators.

## Collection objects in test framework
The `Collection` object was not initialized correctly when constructed from `CassValue`. An issue is described in detail in a corresponding commit.

## Modified tests for collections
Due to the two previous bugs, the tests for collections were modified a bit in the past. Since the issues are fixed, I reverted these changes and the tests now contain original logic from the upstream.

## Duration tests for cassandra
Enabled duration tests for cassandra.

## Scylla version in CI
Bumped Scylla version in CI to `6.0.0`.

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.
- [x] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.

### CODE REVIEW

**Comment by muzarski** [comment]
Rebased on master

File: tests/src/integration/ccm/bridge.cpp [hunk 1]
```diff
@@ -849,19 +849,31 @@ CassVersion CCM::Bridge::get_cassandra_version() {
...
   std::vector<std::string> active_cluster_version_command;
   active_cluster_version_command.push_back(generate_node_name(1));
-  active_cluster_version_command.push_back("version");
+  if (!is_scylla_) {
+    active_cluster_version_command.push_back("version");
+  }
+  else {
+    // For scylla, we need to use versionfrombuild. version always returns 3.0.8.
+    active_cluster_version_command.push_back("versionfrombuild");
+  }
```
Comment (Lorak-mmk) [inline tests/src/integration/ccm/bridge.cpp]: Why not switch the condition around to avoid unnecessary negation?

File: tests/src/integration/tests/test_basics.cpp [hunk 2]
```diff
@@ -343,7 +343,7 @@ CASSANDRA_INTEGRATION_TEST_F(BasicsTests, NoCompactEnabledConnection) {
     }
```
Comment (Lorak-mmk) [inline tests/src/integration/tests/test_basics.cpp:343]: Aren't we going to run into this ` if (!Options::is_cassandra()) {
    if (server_version_ >= "6.0.0") {` branch when we update Scylla to 6.0?
If so, can you fix this in this PR?

**Review by Lorak-mmk — CHANGES_REQUESTED** [review]

File: tests/src/integration/tests/test_basics.cpp (hunk 2 above)
Comment (muzarski) [reply tests/src/integration/tests/test_basics.cpp:343]: No, `Options::is_cassandra()` actually returns `true` for Scylla as well. It's because Scylla identifies as `Apache Cassandra` server (such info is retrieved from `ccm`).

There are 3 possible `CCM:ServerType` enum values:
```cpp

bool Options::is_cassandra() { return server_type_ == CCM::ServerType::CASSANDRA; }

bool Options::is_dse() { return server_type_ == CCM::ServerType::DSE; }

bool Options::is_ddac() { return server_type_ == CCM::ServerType::DDAC; }
```

I'm not sure about the difference between the types, but in Scylla's case, the server type is `CASSANDRA`. `Options::is_scylla_` is a flag responsible for distinguishing between scylla and cassandra.

Comment (Lorak-mmk) [reply tests/src/integration/tests/test_basics.cpp:343]: wth is ddac?! Never heard about it before.

**Comment by muzarski** [comment]
v1.1: addressed review comment

**Review by Lorak-mmk — APPROVED** [review]

File: tests/src/integration/tests/test_basics.cpp (hunk 2 above)
Comment (wprzytula) [reply tests/src/integration/tests/test_basics.cpp:343]: https://www.datastax.com/press-release/datastax-announces-datastax-distribution-apache-cassandratm

File: tests/src/integration/ccm/bridge.cpp [hunk 3]
```diff
@@ -849,19 +849,31 @@ CassVersion CCM::Bridge::get_cassandra_version() {
...
+      size_t version_index = ccm_output.find("ReleaseVersion:");
+      if (version_index != std::string::npos) {
+        ccm_output.replace(0, version_index + 15, "");
+        return CassVersion(trim(ccm_output));
+      }
+
+        // Unable to determine version information from active cluster
+        throw BridgeException("Unable to determine version information from active Cassandra cluster \"" +
+                        get_active_cluster() + "\""); 
   }
```
Comment (wprzytula) [inline tests/src/integration/ccm/bridge.cpp]: Inconsistent indentation? `throw` should probably be indented less.

File: tests/src/integration/ccm/bridge.cpp [hunk 4]
```diff
@@ -849,19 +849,31 @@ CassVersion CCM::Bridge::get_cassandra_version() {
...
 
-  // Unable to determine version information from active cluster
-  throw BridgeException("Unable to determine version information from active Cassandra cluster \"" +
-                        get_active_cluster() + "\"");
+  // versionfrombuild returns a version directly
+  return CassVersion(ccm_output);
```
Comment (wprzytula) [inline tests/src/integration/ccm/bridge.cpp]: For readability, please make the `if` and `if-else` statement, with this in `if (is_scylla)` branch, and the other code in `else` branch.

File: tests/src/integration/ccm/cass_version.hpp [hunk 5]
```diff
@@ -281,7 +281,7 @@ class CassVersion {
     std::string scylla_version_prefix = "release:";
     std::string version(version_string);
     if (version.compare(0, scylla_version_prefix.size(), scylla_version_prefix) == 0) {
-      version = "3.0.8";
+      version.replace(0, scylla_version_prefix.size(), "");
     }
     std::replace(version.begin(), version.end(), '.', ' ');
```
Comment (wprzytula) [inline tests/src/integration/ccm/cass_version.hpp:286]: How this new code actually retrieves the Scylla version? Or, if it's already retrieved, what variable stores it?

File: tests/src/integration/integration.hpp [hunk 6]
```diff
@@ -83,28 +83,28 @@
...
 
-#define CHECK_VERSION(version)                                                      \
+#define CHECK_CASSANDRA_VERSION(version)                                                      \
   do {                                                                              \
     CCM::CassVersion cass_version = this->server_version_;                          \
     if (!Options::is_cassandra()) {                                                 \
       cass_version = static_cast<CCM::DseVersion>(cass_version).get_cass_version(); \
     }                                                                               \
-    if (cass_version < #version) {                                                  \
+    if (!Options::is_scylla() && cass_version < #version) {                                                  \
```
Comment (wprzytula) [inline tests/src/integration/integration.hpp]: Please add a comment mentioning why only Cassandra version is checked now and maybe a `TODO: Scylla version checks (when needed)`.

File: .github/workflows/build.yml [hunk 7]
```diff
@@ -51,7 +51,8 @@ jobs:
 :CompressionTests.*\
 :LoggingTests.*\
 :-PreparedTests.Integration_Cassandra_PreparedIDUnchangedDuringReprepare\
-:ExecutionProfileTest.InvalidName"
+:ExecutionProfileTest.InvalidName\
+:*NoCompactEnabledConnection"
```
Comment (wprzytula) [inline .github/workflows/build.yml:55]: IIUC, this commit makes the CI pass again, after the previous commit makes if fail due to disabling version filtering for Scylla.
We shouldn't have any commits that do not pass tests, because those break bisectability. A quick fix is to swap this commit with the previous one.

File: tests/src/integration/objects/collection.hpp [hunk 8]
```diff
@@ -198,11 +198,8 @@ class Collection : public Object<CassCollection, cass_collection_free> {
       // Initialize the iterator
       iterator_ = cass_iterator_from_collection(value);
 
-      // Determine if the collection is empty (null)
-      const CassValue* check_value = cass_iterator_get_value(iterator_.get());
-      if (check_value) {
-        is_null_ = false;
-      }
+      // We already checked that collection is not null.
+      is_null_ = false;
```
Comment (wprzytula) [inline tests/src/integration/objects/collection.hpp]: While this is an unpleasant peculiarity, empty collections seem to be identical to NULL values for the DB. See https://github.com/scylladb/scylla-rust-driver/pull/1007 for reference.

Comment (wprzytula) [reply tests/src/integration/objects/collection.hpp]: Have you considered making `position` field a non-`Option`?

Comment (wprzytula) [reply tests/src/integration/objects/collection.hpp]: I don't want to dive too deep into the code (because I have other tasks to do), but I think we should do our best to make the cpp-rust-driver's behaviour consistent with what the official cpp-driver's tests expect.

**Review by wprzytula — CHANGES_REQUESTED** [review]

File: tests/src/integration/objects/collection.hpp (hunk 8 above)
Comment (Lorak-mmk) [reply tests/src/integration/objects/collection.hpp]: > I don't want to dive too deep into the code (because I have other tasks to do), but I think we should do our best to make the cpp-rust-driver's behaviour consistent with what the official cpp-driver's tests expect.

It was my understanding that this is what this PR does. Is that not the case?

File: tests/src/integration/ccm/cass_version.hpp (hunk 5 above)
Comment (muzarski) [reply tests/src/integration/ccm/cass_version.hpp:286]: > Or, if it's already retrieved, what variable stores it?

The `version` variable.

File: tests/src/integration/objects/collection.hpp (hunk 8 above)
Comment (muzarski) [reply tests/src/integration/objects/collection.hpp]: > While this is an unpleasant peculiarity, empty collections seem to be identical to NULL values for the DB. See [scylladb/scylla-rust-driver#1007](https://github.com/scylladb/scylla-rust-driver/pull/1007) for reference.

Good catch. I'll add the `is_null_` initialization here. However, I still think that iterator should not be used for checking if collection is empty. The iterator, when created, is UNINITIALIZED - to retrieve the first value, we should firstly advance the iterator via `cass_iterator_next`. I don't want to advance the iterator just to check if it's empty. I'll adjust the code so we make use of `cass_value_item_count` function, which can be used to see if collection is empty.

**Comment by muzarski** [comment]
v2: addressed review comments

File: tests/src/integration/ccm/bridge.cpp [hunk 9]
```diff
@@ -849,19 +849,32 @@ CassVersion CCM::Bridge::get_cassandra_version() {
...
+  if (is_scylla_) {
+    // For scylla, we need to use versionfrombuild. version always returns 3.0.8.
+    active_cluster_version_command.push_back("versionfrombuild");
+
+    std::string ccm_output = execute_ccm_command(active_cluster_version_command);
+
+    // versionfrombuild returns a version directly
+    return CassVersion(ccm_output);
   }
+  else {
```
Comment (dkropachev) [inline tests/src/integration/ccm/bridge.cpp]: can you please drop this `else`

File: tests/src/integration/integration.hpp [hunk 10]
```diff
@@ -83,28 +83,32 @@
...
       SKIP_TEST_VERSION(cass_version.to_string(), #version)                         \
     }                                                                               \
   } while (0)
 
-#define CHECK_OPTIONS_VERSION(version)                                 \
-  if (Options::server_version() < #version) {                          \
+#define CHECK_OPTIONS_CASSANDRA_VERSION(version)                                 \
```
Comment (dkropachev) [inline tests/src/integration/integration.hpp]: I don't see it is ever used, can we drop it ?

File: tests/src/integration/integration.hpp [hunk 11]
```diff
@@ -83,28 +83,32 @@
   SKIP_TEST("Unsupported for Apache Cassandra Version "          \
             << server_version_string << ": Server version " << version_string << "+ is required")
 
-#define CHECK_VERSION(version)                                                      \
+// Currently, we only check for the version if tests are being run against
+// Cassandra cluster. It's because, some of the tests were unnecessarily
+// skipped for Scylla. In the future (once it's needed) we might
+// do some version restrictions for Scylla clusters as well.
+#define CHECK_CASSANDRA_VERSION(version)                                                      \
```
Comment (dkropachev) [inline tests/src/integration/integration.hpp]: Since we are renaming it, can we rename it to somehting more telling, like `SKIP_IF_CASSANDRA_VERSION_LT`

File: tests/src/integration/objects/collection.hpp [hunk 12]
```diff
@@ -194,15 +194,17 @@ class Collection : public Object<CassCollection, cass_collection_free> {
...
+      // Check if collection is empty (null).
+      // Scylla does not distinguish between an empty collection and NULL value.
+      // See: https://opensource.docs.scylladb.com/stable/cql/types.html#sets
+      size_t collection_size = cass_value_item_count(value);
+      if (collection_size > 0) {
+        is_null_ = false;
+      }
 
       // Initialize the iterator
       iterator_ = cass_iterator_from_collection(value);
```
Comment (dkropachev) [inline tests/src/integration/objects/collection.hpp:207]: Can you drop this line then ?

**Review by dkropachev — CHANGES_REQUESTED** [review]

File: tests/src/integration/objects/collection.hpp (hunk 12 above)
Comment (muzarski) [reply tests/src/integration/objects/collection.hpp:207]: No. `iterator_` is a field. This code is called when constructor is called, and so this line initializes a field of a new object.

**Comment by muzarski** [comment]
v2.1: Addressed @dkropachev 's review comments.
